All: RationalNumbers HugeInteger

RationalNumbers: TestRationalNumbers.class RationalNumbers.class

TestRationalNumbers.class: TestRationalNumbers.java
	javac TestRationalNumbers.java

RationalNumbers.class: RationalNumbers.java
	javac RationalNumbers.java

HugeInteger: TestHugeInteger.class HugeInteger.class

TestHugeInteger.class: TestHugeInteger.java
	javac TestHugeInteger.java

HugeInteger.class: HugeInteger.java
	javac HugeInteger.java

clean:
	rm -f *.class
